name: RT-FM
version: 2.1.24
abstract: RT FM Extension
license: GPL version 2
distribution_type: module
requires:
  perl: 5.8.0
  Text::WikiFormat: 0
  RT: 3.4.2
  Tree::Simple: 0
  HTML::TreeBuilder: 0
  Time::ParseDate: 0
  HTML::FormatText: 0
  YAML: 0
no_index:
  directory:
    - bin
    - etc
    - html
    - po
    - sbin
    - inc
generated_by: Module::Install version 0.36
