--- 
abstract: RT FM Extension
distribution_type: module
generated_by: Module::Install version 0.670
license: GPL version 2
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: RTFM
no_index: 
  directory: 
    - bin
    - etc
    - html
    - po
    - sbin
    - inc
    - t
requires: 
  HTML::FormatText: 0
  HTML::TreeBuilder: 0
  RT: 3.4.2
  Text::WikiFormat: 0
  Time::ParseDate: 0
  Tree::Simple: 0
  YAML: 0
  perl: 5.8.0
version: 2.3.0
